# Generated by Django 3.2.25 on 2025-06-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.TextField(help_text='List of coordinates as JSON string: [[x1, y1], [x2, y2], ...]')),
            ],
        ),
    ]
